# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33870cd0f3acfa44a802096c50c269ff72fdd54b8d203fc8deb4ac2cb0387b23e2b778e3d2aec175ef06d690dc2da7dca9503e265e285fa388fe16a4c46cb1e6

test:
  secret_key_base: 289130f9483eac31db2a05d41767f40eae32f403b7bfbbdb76de400482089326d0fd40e314d01407b5afba09e374af4d6918cb80db96f8a52ba17d8ebc05cff7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
